spring.application.name=spb7_rest_20260611

spring.datasource.driverClassName:org.h2.Driver
spring.datasource.url:jdbc:h2:mem:test
spring.datasource.username:sa
spring.datasource.password:
spring.h2.console.enabled:true

#Swagger-UIを利用するための指定
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html